### ISSUE TITLE
difficult to create subclasses of FSA::Rules 

### ISSUE THREAD

**Issue by glasswalk3r** [theory/fsa-rules#9]
This is more a feature request than a bug or issue.

It's difficult to subclass some methods from FSA::Rules.

For example, I would like to create direct getter/setter for keys in:

``` Perl
$machines{$self}->{notes}->{my_key}

```

But I can't directly access %machines from a subclass of FSA::Rules.
For additional speed, I would like to avoid completely having to fall into `if` statements of `notes()` method, since I'll know if I want to use a getter or a setter.

That would be possible if `%machines` is declared with `our`, but that would break some principles of OOP.

On the other hand, all I need is to have a place holder that can be accessed efficiently and shared amount all states (not all machines). Maybe it is better to have a new attribute and methods after all?

**Comment by theory** [comment]
- To what extent is this issue addressed by #8?
- Perhaps `note` and `set_note` methods would solve the problem?
- I'm not following your suggestion/question in the last paragraph.

This is some crazy micro-optimization. I'm impressed that your app is so crazy optimized already that you're down to a few milliseconds here and there in FSA::Rules!

**Comment by glasswalk3r** [comment]
This is completely related to my latest pull request.
I think separating getter from setter would have the best trade-off between code readability and performance.
I completely agree that this is micro-optimization... the thing is, till now was one of the easiest thing to improve. :-)
`FSA::Rules::notes` is not the slowest part, but is the most invoke method/function (sorry if this is a bit off-topic):

# Top 15 Subroutines

| Calls | P | F | Exclusive Time | Inclusive Time | Subroutine |
| --- | --- | --- | --- | --- | --- |
| 745 | 1 | 1 | 312s | 312s | IO::Select::::CORE:sselect IO::Select::[CORE:sselect](IO-Select-pm-441-line.html#IO__Select__CORE_sselect) (opcode) |
| 2 | 1 | 1 | 10.0s | 10.0s | Test::Siebel::Srvrmgr::Daemon::::CORE:sleep Test::Siebel::Srvrmgr::Daemon::[CORE:sleep](t-Test-Siebel-Srvrmgr-Daemon-pm-581-line.html#Test__Siebel__Srvrmgr__Daemon__CORE_sleep) (opcode) |
| 4 | 1 | 1 | 4.00s | 4.00s | Siebel::Srvrmgr::Daemon::Heavy::::CORE:sleep Siebel::Srvrmgr::Daemon::Heavy::[CORE:sleep](Class-MOP-Package-pm-114-line.html#Siebel__Srvrmgr__Daemon__Heavy__CORE_sleep) (opcode) |
| 20709 | 2 | 1 | 547ms | 1.50s | Siebel::Srvrmgr::ListParser::::set_buffer Siebel::Srvrmgr::ListParser::[set_buffer](Siebel-Srvrmgr-ListParser-pm-476-line.html#302) |
| 248 | 1 | 1 | 503ms | 5.96s | Siebel::Srvrmgr::ListParser::::parse Siebel::Srvrmgr::ListParser::[parse](Siebel-Srvrmgr-ListParser-pm-476-line.html#589) |
| 185 | 1 | 1 | 408ms | 1.01s | Siebel::Srvrmgr::ListParser::Output::Tabular::::**ANON**[lib/Siebel/Srvrmgr/ListParser/Output/Tabular.pm:200] Siebel::Srvrmgr::ListParser::Output::Tabular::[**ANON**[lib/Siebel/Srvrmgr/ListParser/Output/Tabular.pm:200]](Siebel-Srvrmgr-ListParser-Output-Tabular-pm-707-line.html#83) |
| 249 | 1 | 1 | 398ms | 645ms | Siebel::Srvrmgr::Daemon::Heavy::::_process_stdout Siebel::Srvrmgr::Daemon::Heavy::[_process_stdout](Siebel-Srvrmgr-Daemon-Heavy-pm-121-line.html#888) |
| 21203 | 1 | 1 | 391ms | 603ms | Siebel::Srvrmgr::ListParser::FSA::::**ANON**[lib/Siebel/Srvrmgr/ListParser/FSA.pm:109] Siebel::Srvrmgr::ListParser::FSA::[**ANON**[lib/Siebel/Srvrmgr/ListParser/FSA.pm:109]](Siebel-Srvrmgr-ListParser-FSA-pm-492-line.html#77) |
| 176431 | 8 | 3 | 316ms | 316ms | FSA::Rules::::notes FSA::Rules::[notes](FSA-Rules-pm-493-line.html#831) |
| 21203 | 1 | 1 | 262ms | 1.11s | FSA::Rules::::try_switch FSA::Rules::[try_switch](FSA-Rules-pm-493-line.html#598) |
| 42004 | 16 | 4 | 241ms | 329ms | Log::Log4perl::Logger::::**ANON**[Log/Log4perl/Logger.pm:785] Log::Log4perl::Logger::[**ANON**[Log/Log4perl/Logger.pm:785]](Log-Log4perl-Logger-pm-450-line.html#777) |
| 29257 | 49 | 2 | 222ms | 322ms | FSA::State::::notes FSA::State::[notes](FSA-Rules-pm-493-line.html#1357) |
| 19217 | 1 | 1 | 218ms | 276ms | Siebel::Srvrmgr::ListParser::Output::Tabular::Struct::Fixed::::get_fieldsSiebel::Srvrmgr::ListParser::Output::Tabular::Struct::Fixed::[get_fields](Siebel-Fixed-pm-710-line.html#103) |
| 27385 | 39 | 5 | 213ms | 233ms | Log::Log4perl::Logger::::**ANON**[Log/Log4perl/Logger.pm:795] Log::Log4perl::Logger::[**ANON**[Log/Log4perl/Logger.pm:795]](Log-Log4perl-Logger-pm-450-line.html#793) |
| 16348 | 1 | 1 | 163ms | 384ms | Siebel::Srvrmgr::ListParser::FSA::::**ANON**[lib/Siebel/Srvrmgr/ListParser/FSA.pm:248] Siebel::Srvrmgr::ListParser::FSA::[**ANON**[lib/Siebel/Srvrmgr/ListParser/FSA.pm:248]](Siebel-Srvrmgr-ListParser-FSA-pm-492-line.html#243) |

**Comment by theory** [comment]
I can add those accessors. But take note of this comment in the docs:

> The C<notes()> method provides a place to store arbitrary data in the state
> machine, just in case you're not comfortable using the FSA::Rules object
> itself, which is an empty hash.

In other words, why not just use your FSA::Rules object as a hash of notes directly? It's completely empty, ready for you to use, and would be _much_ more efficient than using `notes()`.

**Comment by theory** [comment]
That's a branch for you to try the note methods. But if direct hash access will work for you (and would be faster than these methods!), I expect I won't merge it.

**Comment by glasswalk3r** [comment]
Hi David,

I gave a try to use direct hash access inside the class and it was even faster as expected. I didn't want to expose the hash to external code, so I create new methods to get and set the data when necessary to be done externally. Didn't saw any major impact after that, so I think is a good trade-off between speed and keep maintain encapsulation.

I would suggest using a separated getter/setter for note() method if you think it a good idea. Don't see it as necessary to get this speed improvement. Maybe you can keep note() as is, while maintaining the getter and setter, marking it as obsolete and replace it after some time.

Thanks for the help and suggestions anyway.

**Comment by theory** [comment]
Meh. The entire reason the objects don't keep their state in the underlying hash object is so that users can use the has directly with no risk of collision. Far and away the fastest way to go, and documented and supported, too. But might be useful to add accessors for your specific attributes in a subclass.
